import { ArrowRight, Check, Terminal, Files, Image, Scissors, FileText } from 'lucide-react';
import { SiteHeader, SiteFooter } from '../components/site-chrome';
const routes = ['PNG → JPEG','PNG → TIFF','Image → PDF','PDF → selected pages','MOV → M4A','Images → one PDF','WAV → MP3','CSV → JSON','Scan → editable text','Image → smaller dimensions','PDF page → PNG','TSV → CSV'];
const actions = [
  {family:'IMAGES',title:'Images',text:'Convert, crop, resize or fit a size limit.',icon:Image},
  {family:'PDFS',title:'PDFs',text:'Combine, reorder, rotate, split, compress and extract pages, images or text.',icon:Files},
  {family:'AUDIO & VIDEO',title:'Audio & video',text:'Convert, extract audio and trim recordings.',icon:Scissors},
  {family:'TEXT & TABLES',title:'Text & tables',text:'Convert CSV, TSV and flat JSON; recognize text in scans locally.',icon:FileText},
];
function SectionHeading({number,label,title,children}:{number:string;label:string;title:string;children?:React.ReactNode}){return <div className="section-heading"><h2>{title}</h2>{children}</div>}
export default function Home(){return <><SiteHeader/><main id="main-content" className="v2-main">
  <section className="v2-hero wrap"><div className="hero-story"><h1>The file you have.<br/><span>The file you need.</span></h1><p>Convert, resize, combine and trim files on your Mac. Drop them in, choose an action and save the result. Your originals stay untouched.</p><div className="hero-actions"><a className="button primary" href="#get-fileform">Release status <ArrowRight size={17} aria-hidden="true"/></a><a className="button secondary" href="#cli">Free CLI</a></div></div><aside className="hero-facts" aria-label="Fileform at a glance"><dl><div><dt>PLATFORM</dt><dd>macOS 14+ target</dd></div><div><dt>PROCESSING</dt><dd>Local</dd></div><div><dt>ENGINE</dt><dd>Free &amp; open source</dd></div><div><dt>MAC APP</dt><dd>In development</dd></div></dl></aside></section>
  <figure className="app-showcase wrap"><img src="/app-workspace.png" width="4718592" height="4292935744" alt="Fileform’s native PDF workbench with four arranged pages split into two PDFs." fetchPriority="high"/></figure>
  <div className="route-ticker" aria-label="Examples of available transformations"><div className="route-track">{[0,1].map(copy=><div className="route-copy" key={copy} aria-hidden={copy===1?true:undefined}>{routes.map(route=><a href="/formats" tabIndex={copy===1?-1:undefined} key={route}>{route}<span aria-hidden="true">·</span></a>)}</div>)}</div></div>
  <section id="what" className="v2-section outcome-section"><SectionHeading number="01" label="WHAT IT DOES" title="File tools in one place"><p><a href="/formats">Formats and limits</a></p></SectionHeading><div className="outcome-grid">{actions.map(({icon:Icon,...action})=><article key={action.family}><div className="outcome-label"><Icon size={19} aria-hidden="true"/></div><h3>{action.title}</h3><p>{action.text}</p></article>)}</div></section>
  <section id="how" className="v2-section how-section"><SectionHeading number="02" label="HOW IT WORKS" title="Drop. Choose. Save."/><ol className="step-grid"><li><div className="step-example drop-example">Drop your files here</div><h3>Add files</h3><p>Drag them in, use the picker or paste a direct media link.</p></li><li><div className="step-example"><span>JPEG image</span><span className="example-pill">under 10 MB</span></div><h3>Choose an action</h3><p>Set the format, size or selection. Review changes before saving.</p></li><li><div className="step-example result-example"><span><Check size={15} aria-hidden="true"/> cover-converted.jpg</span><small>Open · Reveal · Share</small></div><h3>Use the results</h3><p>Open, reveal, share or drag saved files into another app.</p></li></ol></section>
  <section id="direct" className="v2-section split-feature"><SectionHeading number="03" label="DIRECT EDITS" title="Trim and crop visually"><p>Drag the trim range and preview your selection. Exact cuts re-encode; eligible fast cuts show their actual boundaries. Crop images with drag handles or aspect presets, with Undo available.</p></SectionHeading><figure className="feature-screen"><img src="/trim-workspace.png" width="4718592" height="4292935744" loading="lazy" alt="The native audio trimmer with a waveform, selection controls, playback and output settings."/></figure></section>
  <section className="v2-section split-feature batch-feature"><figure className="feature-screen"><img src="/crop-workspace.png" width="4718592" height="4292935744" loading="lazy" alt="An original image with a square crop beside the verified square JPEG result."/></figure><SectionHeading number="04" label="ONE FILE OR MANY" title="One file or a batch"><p>Convert files separately or combine PDFs and images into one document. Check the order and page count, apply compatible batch settings and choose output names.</p></SectionHeading></section>
  <section id="cli" className="v2-section engine-section"><SectionHeading number="05" label="PAID APP, OPEN ENGINE" title="Free engine. Paid Mac app."/><div className="engine-grid"><article><div className="card-heading"><h3>Fileform for Mac</h3><span className="status-pill">IN DEVELOPMENT</span></div><p>Native previews, PDF organization, waveform trimming and saved setups.</p><a href="/download" className="text-link">Release status <ArrowRight size={16} aria-hidden="true"/></a></article><article><div className="card-heading"><h3><Terminal size={20} aria-hidden="true"/> fileform-core</h3><span className="status-pill">FREE &amp; OPEN SOURCE</span></div><p>The same engine for your terminal. No app licence or account required.</p><pre><code>fileform fit cover.png --to jpeg --max-bytes 10000000</code></pre><div className="inline-links"><a href="/docs">CLI guide</a><a href="https://github.com/goamaan/fileform-core">Source on GitHub ↗</a></div></article></div></section>
  <section id="get-fileform" className="v2-section get-section"><SectionHeading number="06" label="GET IT" title="Get Fileform"><p>The signed Mac download and checkout aren’t available yet. Pricing and trial terms will be published before launch.</p><div className="hero-actions"><a className="button primary" href="/download">Release status <ArrowRight size={17} aria-hidden="true"/></a><a className="text-link" href="/docs">Use the free CLI</a></div><p className="small-copy">Local conversions run on your Mac. Direct-link lookup and download contact the source; disable them in Settings.</p></SectionHeading></section>
</main><SiteFooter/></>}
